### ISSUE TITLE
Output for first Chapter 1 example is completely incorrect and makes not sense why 

### ISSUE THREAD

**Issue by jonahvsweb** [PacktPublishing/Python-Automation-Cookbook-Second-Edition#1]
Hi, I'm new to Python and just picked up the book. I've setup my environments just fine, but recently updated Python 2.7 to Python 3.7. As I mentioned, everything is working fine up to the point of the first example script in Chapter 1 ( `recipe_format_strings_step1.py`). 

When I run this file in the console, I get this output: 
```
REVENUE | PROFIT | PERCENT
--------------------------
  1,000 |    +10 |   0.00%
  2,000 |    +17 |   0.00%
  2,500 |   +170 |   0.00%
  2,500 |   -170 | -100.00%
```
I've literally copied and pasted this raw code example in this repo and still no luck, same output as above for me. I imagining it's some quirkiness with Python I'm unaware of, but due to my newness with Python, the recent update from 2.7 to 3.7, I'm not even sure what to Google or look up. 

I don't even logically understand how I'm getting `-100.00%` on the final percent value with the simple division of -170/2500 (output: `-0.068`). It's like adding two decimal places and rounding down or something "under the hood" (-68% rounded down to -100% and then also adding the two decimal places again as defined by `.2%` in the `TEMPLATE` definition; I'm so confused)? Any help would be appreciated.

**Comment by jaimebuelta** [comment]
Are you sure that you are using `python3.7` to run the script? Given the result, it seems like you are using `python2.7`.

the key detail is here 

    percent = profit / revenue

In Python3, this will produce a float result, while in Python2 it will be an int result. The way it works in python2 is actually a `floor division`, rounding to the _lowest_ integer, so for example 5/3 will return 1. This is different to the _nearest_ integer.

with the operation -170 / 2700, the lowest integer is actually -1, you can check doing in Python2

```
Python 2.7.17 (default, Oct 24 2019, 12:57:47)
[GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> -170/2700
-1 
```

while in Python3

```
Python 3.8.6 (default, Oct  8 2020, 14:06:32)
[Clang 12.0.0 (clang-1200.0.32.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> -170/2700
-0.06296296296296296
```

For a result similar in Python2, you need to change it to 

    percent = (1.0 * profit) / revenue

forcing to do a float division.

Hope this explains the behaviour 

(You can see the Python docs difference between https://docs.python.org/2/tutorial/introduction.html?highlight=division#numbers and https://docs.python.org/3.7/tutorial/introduction.html?highlight=division#numbers )
