### ISSUE TITLE
Suggested change to README.md

### ISSUE THREAD

**Issue by carltyndall** [PacktPublishing/Python-Automation-Cookbook-Second-Edition#2]
Is:
Using a problem-solution-based approach, we'll show how you can automate all the boring stuff and let your computer do it for you instead **of** using the Python programming language. 

Suggested:
Using a problem-solution-based approach, we'll show how you can automate all the boring stuff and let your computer do it for you instead **by** using the Python programming language.

**Comment by gaurav-packt** [comment]
Thanks for your suggestion. We'll surely look into it and if deemed appropriate we will incorporate the suggestion,
